### ISSUE TITLE
PrimeNG support: jQuery is not defined

### ISSUE THREAD

**Issue by AlexVFornazieri** [sean-perkins/angular-electron-seed#11]
Hello guys,

I was trying the PrimeNg template in this boilerplate project, but I could not get the jQuery to work, the same is not defined.

Searching in google found a possible solution, disable node integration, setting "BrowserWindow.nodeIntegration" to false.

But, as far as I could tell, this property does not exist when using the main Electron process written in Type Script.

Could someone help me with this?

Thank you everyone for the attention.

**Comment by sean-perkins** [comment]
You could try this issue: https://github.com/primefaces/primeng/issues/256

Or this example repo to diagnose the differences: https://github.com/Mrtcndkn/PrimeNG-Electron

As a good practice, you shouldn't be using JQuery in an Angular environment. That's one of the reasons I dislike PrimeNg, outside of their poor user interface design and nomenclature. 

As this issue does not relate to the seed, but to external integrations; I am closing it.
