### ISSUE TITLE
Failed to execute `npm run start`

### ISSUE THREAD

**Issue by Elderry** [sean-perkins/angular-electron-seed#2]
After `npm i`, `npm run start` complains:
```
> angular-electron-seed@0.0.0 build.tasks C:\Users\<user>\Projects\Personal\angular-electron-seed
> tsc tasks/*.ts --outDir tasks

error TS6053: File 'tasks/*.ts' not found.
```

**Comment by sean-perkins** [comment]
@Elderry Thanks for reporting the issue!

Can you try manually running `tsc`:

```
tsc tasks/*.ts --outDir tasks
```

And tell me if the error persists for that as well?

**Comment by Elderry** [comment]
Yes, it persists. And I noticed that `tsc` seems doesn't accept wildcard file names.
BTW, I tried this on a Windows 10 machine.

**Comment by sean-perkins** [comment]
@Elderry Good to know. I'll work on moving that task out of NPM and into a gulp task. I'll tag you in a comment when that's available here in the next day or so.

**Comment by sean-perkins** [comment]
@Elderry Please pull the latest off master and let me know if your problem persists. I've moved those scripts to gulp tasks leveraging `gulp-tsc`.

**Comment by Elderry** [comment]
Now it works, however, two error dialog popped.

**Comment by sean-perkins** [comment]
Those errors are related to the live-sync hook. If you run `npm run watch`, it will establish a socket listener to the electron app. The bundle commands strip out the live-sync, so those errors won't be present in the actual build. 

I'm open to feedback on how to enhance that process better. I prioritized live-reload for developers.

**Comment by Elderry** [comment]
Your recent commit introduced new bugs, now `npm run start` complains:
```
ERROR in .../angular-electron-seed/src/app/ngx-electron/ngx-electron.service.ts (11,33): Namespace 'Electron' has no exported member 'AllElectron'.

ERROR in .../angular-electron-seed/src/electron/electron-app.ts (9,36): Namespace 'Electron' has no exported member 'BrowserWindowConstructorOptions'.
```

**Comment by sean-perkins** [comment]
The electron pre-built library includes the typing definition, which means the types dependency is no longer required.

https://github.com/electron-userland/electron-prebuilt/blob/master/electron.d.ts

You most likely need to clear and re-install node modules.
