### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:30080

### ISSUE THREAD

**Issue by raqbit** [sean-perkins/angular-electron-seed#6]
Just trying to run `yarn run start` or `npm run start` (ofc after running `npm install`), electron boots up but gives the following error:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:30080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

**Comment by sean-perkins** [comment]
You will need to run `npm run watch` as well. Unfortunately the live-reload hook with the electron app requires opening up a socket listener. The Angular task tries to connect to this, but obviously warns that it cannot connect, if electron hasn't bound it yet. 

For the production release, I strip out the listener, so you won't see this in the bundles. I'm open to better implementations - I realize this isn't perfect.

**Comment by raqbit** [comment]
Ah, I see. :+1:
