### ISSUE TITLE
Cannot find module 'electron-connect' when running linux bundle

### ISSUE THREAD

**Issue by raqbit** [sean-perkins/angular-electron-seed#7]
As far as I understand this is a development depedency, and I don't know why the bundle is giving this error when run. The "watch" command does work.

My commands:
`npm run build && npm bundle.linux`

Full error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-connect'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename ([path]/bundles/demo-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([path]/bundles/demo-linux-x64/resources/app/electron-app.js:4:26)
    at Object.<anonymous> ([path]/bundles/demo-linux-x64/resources/app/electron-app.js:52:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
111

**Comment by anteAdamovic** [comment]
Same error for windows bundle

**Comment by sean-perkins** [comment]
There's a task during the build process that's supposed to remove that import from the final bundle. I can confirm that it was doing this on Mac. I don't have a Windows machine to test and/or the time to spin-up a linux instance. 

I'm open to a PR for someone to test the script and discover why the find/replace isn't working.

**Comment by manxiaoboo** [comment]
I found a way to solve this question.
Uninstall your gulp-string-replace and install gulp-replace.
If your project has bundle.clean.js, remove it.
Change bundle.clean.ts
```
import * as gulp from 'gulp';
import * as path from 'path';
var replace = require('gulp-replace');

/**
 * Copies the package.json required for Electron to create package/bundles
 */
gulp.task('bundle.clean', () => {
    return gulp.src(path.join(process.cwd(), '/dist/', 'electron-app.js'))
        .pipe(replace('var electron_connect_1 = require("electron-connect");', ' ', { logs: { enabled: true }}))
        .pipe(replace('electron_connect_1.client.create(applicationRef);', ' ', { logs: { enabled: true }}))
        .pipe(gulp.dest(path.join(process.cwd(), '/dist')));
});

```
Then, npm run build.prod && npm run bundle.windows.
The point is gulp-string-replace is not work, so give up it, and welcome gulp-replace.

**Comment by sean-perkins** [comment]
@manxiaoboo Thank you for looking into this. If you want to get commit credit for it, feel free to create a PR. Otherwise I can add this into master later this evening.

**Comment by sean-perkins** [comment]
Let me know if this problem persists after the updates on master.
